---
title: "Utiliser OpenStreetMap et son écosystème avec R"
author:
  - Louis Laurian ^[Centre pour l'analyse spatiale et la géovisualisation - CNRS & Université Paris Cité, louis.laurian@cnrs.fr]
  - Timothée Giraud ^[Centre pour l'analyse spatiale et la géovisualisation - CNRS & Université Paris Cité, timothee.giraud@cnrs.fr]
format: typst
indent: true
bibliography: ref.bib
lang: fr
---

```{=typst}
#align(center)[#strong[Résumé]]
```

OpenStreetMap est une base de données cartographique collaborative initiée en 2004 dans le but de créer et distribuer des données géographiques libres au niveau mondial. Avec plus de dix millions de contributeur.ices en 2025 et une licence permettant aux utilisateurs de l'utiliser librement ([ODbL](https://opendatacommons.org/licenses/odbl/])), cette base de données est devenue une ressource importante, utilisée par de nombreux acteurs et mobilisée dans de nombreux projets scientifiques. 

OpenStreetMap contient des informations très diverses relatives à l'espace public (routes, bâtiments, adresses...). La précision géographique, la complétude et la qualité des données s'améliore avec le temps, notamment via les contributions institutionnelles utilisant des technologies GPS précises [@Hennig2019]. Cette précision s'avère particulièrement juste pour le réseau routier [@MORADI20211]. 

OpenStreetMap, comme Google Maps, propose des cartes interactives accessibles en ligne et plusieurs services proposent d'autres fonctionnalités s'appuyant sur la base de données. 
OpenStreetMap, et les services qui l'utilisent, sont facilement mobilisables directement depuis R grace à une série de packages dédiés que nous présenterons lors de cette communication. 
Les tuiles raster qui sous-tendent la plupart des cartes interactives sont ainsi facilement téléchargées et combinées avec le package `maptiles` [@maptiles].
Les packages `osmdata` [@osmdata] et `osmextract` [@osmextract] servent à télécharger directement les objets spatiaux depuis le base de données.
Le package `maposm` [@maposm] fournit (en s'appuyant sur `osmdata`) des couches géographiques particulièrement adaptées à la cartographie.
Le package `tidygeocoder`[@tidygeocoder] donne accès à de nombreux géocodeurs en ligne dont Nominatim qui utilise OpenStreetMap.
Enfin les packages `osrm`[@osrm] et `valh`[@valh] interfacent respectivement les services OSRM et Valhalla pour le calcul d'itinéraires, de matrices de distances ou d'isochrones. 
Nous contribuons par ailleurs activement à cet écosystème en développant certains des packages évoqués.

**Mots-clefs** : Cartographie - Package - OpenStreetMap - Géocodage - Données spatiales 





